# Default = false
programmerArtEpoxy: false

# Default = true
configEnergyDrainDrive: true

# Default = 0.25f
driveEnergyDrainBase: 0.25

# Default = true
yellowRutherfordium: true

# Default = true
harderGold: true

# Default = true
harderPlatline: true

# Default = true
harderTungsten: true

# Default = true
harderIndium: true

# Default = true
harderNaquadah: true

# Default = true
harderYCBO: true

# Default = true
removeCircuitAssemblerRecipes: true

# Default = true
removeLargeCircuitAssembler: true

# Default = 20 seconds
reactorMeltdownTime: 20

# Default = true
darkerSteel: true

VOM1Blacklist:
  - triniite
  - trinium
  - duranium
  - tritanium
  - rutherfordium
  - californium
  - curium
  - seaborgium
  - berkelium
  - fermium
  - einsteinium
  - dubnium
  - bohrium

VOM2Blacklist:
  - trinium
  - fermium
  - bohrium
  - seaborgium
  - einsteinium

VOM3Blacklist:
  - bohrium
  - fermium

